# Generated by Django 4.1.4 on 2022-12-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('mailing', 'client')},
        ),
    ]
